env:
  browser: true
  node: true
extends:
  - 'plugin:react/recommended'
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  require-jsdoc: 0
  react/prop-types: 0
